name: route_flutter_bloc
description: Improve Flutter BLoC performance with navigation-aware widgets. Avoid rebuilds and side-effects when screens are hidden, and automatically respond when the page becomes visible again — but only if the state actually changed while it was hidden. Smart behavior, full control, zero boilerplate.
repository: https://github.com/88888888oleg/route_flutter_bloc
topics: [bloc, state-management]
version: 9.1.1

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
