name: route_flutter_bloc
description: Improve Flutter BLoC performance with navigation-aware widgets. Skip rebuilds and side-effects when screens are hidden. React on resume only if state changed.
repository: https://github.com/88888888oleg/route_flutter_bloc
topics: [bloc, state-management]
version: 9.1.2

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
